---
global:
  storageClass: ceph-block

postgresql:
  persistence:
    size: 2Gi

  volumePermissions:
    enabled: false
    securityContext:
      runAsUser: "auto"

  securityContext:
    enabled: false

  shmVolume:
    chmod:
      enabled: false

  containerSecurityContext:
    enabled: false
