apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: ceph-local-block
  namespace: local-storage
  labels:
    app: rook-ceph
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: node-role.kubernetes.io/storage
          operator: Exists
  storageClassDevices:
    - storageClassName: ceph-local-storage
      volumeMode: Block
      devicePaths:
        - /dev/vdb
