apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  creationTimestamp: "2020-11-26T13:32:50Z"
  generation: 4
  managedFields:
  - apiVersion: integreatly.org/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:config:
          .: {}
          f:auth:
            .: {}
            f:disable_signout_menu: {}
          f:auth.anonymous:
            .: {}
            f:enabled: {}
          f:log:
            .: {}
            f:level: {}
            f:mode: {}
          f:security:
            .: {}
            f:admin_password: {}
            f:admin_user: {}
        f:dashboardLabelSelector: {}
        f:ingress:
          .: {}
          f:enabled: {}
          f:hostname: {}
    manager: Mozilla
    operation: Update
    time: "2020-11-26T13:32:50Z"
  - apiVersion: integreatly.org/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:ingress:
          f:targetPort: {}
    manager: oc
    operation: Update
    time: "2020-11-26T13:57:55Z"
  - apiVersion: integreatly.org/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:dashboards: {}
        f:failedPlugins: {}
        f:installedPlugins: {}
        f:message: {}
        f:phase: {}
    manager: grafana-operator
    operation: Update
    time: "2020-12-08T09:12:19Z"
  name: grafana
  namespace: monitoring-example-1
  resourceVersion: "10217393"
  selfLink: /apis/integreatly.org/v1alpha1/namespaces/monitoring-example-1/grafanas/grafana
  uid: 0c247742-5491-45d0-89da-9bbc69d95674
spec:
  adminPassword: redhat
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: secret
      admin_user: root
  dashboardLabelSelector:
  - matchExpressions:
    - key: app
      operator: In
      values:
      - grafana
  ingress:
    enabled: true
    hostname: grafana.apps.ocp.lan.stderr.at
    targetPort: grafana
    tlsEnabled: false
status:
  dashboards: null
  failedPlugins: null
  installedPlugins: null
  message: success
  phase: reconciling
