kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-operators

bases:
  - ../../base

patches:
-  target:
     kind: Subscription
     name: gitlab-runner-operator
   patch: |-
    - op: replace
      path: /spec/channel
      value: 'stable'
    - op: replace
      path: /spec/startingCSV
      value: 'gitlab-runner-operator.v1.3.0'
