apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: quay-bucket
  namespace: redhat-quay
spec:
  generateBucketName: quay
  storageClassName: bucket-sc
  additionalConfig:
    maxObjects: "10000"
    maxSize: "10G"
