apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: stderr-quayecosystem
  namespace: redhat-quay
spec:
  quay:
    externalAccess:
      hostname: quay.apps.ocp.lan.stderr.at
      configHostname: quay-config.apps.ocp.lan.stderr.at
      tls:
        secretName: custom-quay-ssl
        termination: passthrough
    imagePullSecretName: redhat-pull-secret
    superuserCredentialsSecretName: superuser
    enableRepoMirroring: true
    database:
      volumeSize: 10Gi
      credentialsSecretName: quay-database
    envVars:
      - name: DEBUGLOG
        value: "true"
    registryBackends:
      - name: ceph-bucket
        rados:
          accessKey: FTJYWD3LINGBI4HK8W6H
          secretKey: mrBNpo9CaqvkjWKEuSR21xovGckrfLkf337lyTrD
          secure: false
          bucketName: quay-98d678dd-4126-42e9-8e3f-9532a02c19e5
          hostname: rook-ceph-rgw-object-store.rook-ceph.svc.cluster.local
          port: 80
          storagePath: /
  clair:
    imagePullSecretName: redhat-pull-secret
    enabled: true
    database:
      volumeSize: 10Gi
      credentialsSecretName: clair-database
