apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: htpass-secret
  namespace: openshift-config
data:
  htpasswd: YWRtaW46JDJ5JDA1JFd4akMuWFRFR1BtME9NSE1RbjQ2ZU9kNlJES2lVU2NHcGh1cC9mc1hxczFGMTNVaDB2aEVhCg==
